### ISSUE TITLE
ユーザメニューを作成

### ISSUE THREAD

**Issue by averak** [fy23-gw-gackathon/reportify-frontend#42]
## 概要

Avatarタグは使用しなくて良さそう。

<img width="167" alt="スクリーンショット 2023-05-09 15 55 00" src="https://user-images.githubusercontent.com/50389029/237017918-68e8fda2-40a3-4f7e-b0d3-a1a56e5954aa.png">

**Comment by gari8** [comment]
userIdからidenticon生成で良さそう
https://zenn.dev/sikkim/articles/088389c5fcc1fd
